### ISSUE TITLE
Feature request: Set working directory option

### ISSUE THREAD

**Issue by mind12** [memstechtips/WIMUtil#1]
Hello,

Instead of using c:\wimutil by default it would be better to add an option to the first menu to pick the working directory. Could be default to the current one. 
Not everybody has so much space on C: to download, extract and create another iso there.

Thank you
mind12

**Comment by mind12** [comment]
CTT like solution would be perfect:
![image](https://github.com/user-attachments/assets/3eba57cd-cb42-4481-a340-724ea9ddc28e)

**Comment by memstechtips** [comment]
Feature added in #19
