### ISSUE TITLE
Unable to run utility without Internet Explorer.

### ISSUE THREAD

**Issue by jrafaelmdo** [memstechtips/WIMUtil#10]
Unable to run script as I do not have Internet explorer

Error loading XAML from URL: The response content cannot be parsed because the Internet Explorer engine is not available, or Internet Explorer's first-launch configuration is not complete. Specify the UseBasicParsing parameter and try again.
Failed to load the XAML file. Exiting script.
Press Enter to continue...:

Thank you.

**Comment by memstechtips** [comment]
This should be fixed in: #12
Please reopen if it's not.
