### ISSUE TITLE
Not enough space...

### ISSUE THREAD

**Issue by Maxarian** [memstechtips/WIMUtil#14]
I'm getting this error when selecting ISO.  Doesn't matter which ISO I choose.
This is on a clean fresh install of Windows 10.
![WIMUtil error](https://github.com/user-attachments/assets/23838a42-241c-4171-94b4-67512c247c65)

Thanks

Max

**Comment by memstechtips** [comment]
Hi there,

Could you try with the latest version, I just did an update in #19

**Comment by Maxarian** [comment]
Apologies for the late reply.
I realised I was using Windows 10.
Using Windows 11 I was able to continue to the end (mostly - creates an error code 0x80070001 - 0x4002F.  seeking solution so closing this 'ticket').

Thanks

Max.
