### ISSUE TITLE
Date mismatch.

### ISSUE THREAD

**Issue by Maxarian** [memstechtips/WIMUtil#15]
Hi Everyone.
Cannot complete Step 5 as receiving message 'Signature date mismatch! oscdimg may not be from Microsoft.'
![Date mismatch](https://github.com/user-attachments/assets/177f4eba-4916-410c-80e9-b3c50af32c02)

Any ideas please?

Thanks

Max.

**Comment by memstechtips** [comment]
Hi there,

Could you try with the latest version, I just did an update in #19

**Comment by Maxarian** [comment]
Apologies for the late reply.
I realised I was using Windows 10.
Using Windows 11 I was able to continue to the end (mostly - creates an error code 0x80070001 - 0x4002F.  seeking solution so closing this 'ticket').

Thanks

Max.

**Comment by Maxarian** [comment]
Apologies for the late reply.
I realised I was using Windows 10.
Using Windows 11 I was able to continue to the end (mostly - creates an error code 0x80070001 - 0x4002F.  seeking solution so closing this 'ticket').

Thanks

Max.
