### ISSUE TITLE
"signature date mismatch! oscdimg may not be from Microsoft"

### ISSUE THREAD

**Issue by StarMusa88** [memstechtips/WIMUtil#5]
keep getting Error message  "signature date mismatch oscdimg may not be from Microsoft"

![Screenshot 2024-11-15 174257](https://github.com/user-attachments/assets/7d69c30a-997a-4e87-a11d-9604ee1d7c97)

**Comment by memstechtips** [comment]
C:\Program Files (x86)\Windows Kits\10\Assessment and Deployment Kit\Deployment Tools\amd64\Oscdimg\oscdimg.exe

That's the filepath to where oscdimg.exe is saved.

Could you manually delete it from the folder and then try using WIMUtil again?

Please report back afterwards.

**Comment by StarMusa88** [comment]
The folder is empty.

![Screenshot 2024-11-15 203027](https://github.com/user-attachments/assets/0c567494-948c-48a7-8fc9-567b51f733fc)

**Comment by memstechtips** [comment]
Interesting.

So is the "Get Oscdimg" button disabled in your app or can you click it and when you click it yoi get the error message as described in this issue?

**Comment by CyberSpectra** [comment]
im also getting the same exact error

**Comment by memstechtips** [comment]
Can you guys also share your current OS details?

Windows 10/11 with version number like 24H2 for example.
32bit/64bit/arm64
Are you launching the command via PowerShell or Terminal?

**Comment by CyberSpectra** [comment]
i managed to get it to work for me all i needed to do was close my termanal and delete all wimutil files and make sure the Oscdimg .exe is in the folder C:\Program Files (x86)\Windows Kits\10\Assessment and Deployment Kit\Deployment Tools\amd64\Oscdimg then when i done i redid the process and it worked

**Comment by StarMusa88** [comment]
I'm using powershell.

The "Get Oscdimg" button is not disabled.

So do i need to delete all the Windows kits folder? because I'm not able to find the "Oscdimg .exe'" as shown in my previous reply.

**Comment by memstechtips** [comment]
> I'm using powershell.
> 
> The "Get Oscdimg" button is not disabled.
> 
> So do i need to delete all the Windows kits folder? because I'm not able to find the "Oscdimg .exe'" as shown in my previous reply. 

So just to clarify, if you click on the Get oscdimg button, is that when you see the message that says there is mismatch?

I'm trying to figure out if its only the status message that's wrong or if it's actually the entire process of downloading the oscdimg.exe file.

**Comment by memstechtips** [comment]
> i managed to get it to work for me all i needed to do was close my termanal and delete all wimutil files and make sure the Oscdimg .exe is in the folder C:\Program Files (x86)\Windows Kits\10\Assessment and Deployment Kit\Deployment Tools\amd64\Oscdimg then when i done i redid the process and it worked
> 

Where did you acquire the oscdimg file from and how did you acquire it?

**Comment by StarMusa88** [comment]
memstechtips : Yes,  The Get oscdimg buttonis working, that's when I et the error message.

**Comment by memstechtips** [comment]
> memstechtips : Yes,  The Get oscdimg button is working, that's when I get the error message.
> 
> I'm on Win 11 24H2  64 bit powershell

And it's safe to assume that when clicking the "get" button, it doesn't even download the oscdimg.exe file right? It never even shows up in the folder?

**Comment by spike999uk** [comment]
Had same issue. I had the windows application deployment kit software available so once that was installed all was ok obviously. Assume it just checks the above location to find the program?

**Comment by StarMusa88** [comment]
> > memstechtips : Yes,  The Get oscdimg button is working, that's when I get the error message.
> > I'm on Win 11 24H2  64 bit powershell
> 
> And it's safe to assume that when clicking the "get" button, it doesn't even download the oscdimg.exe file right? It never even shows up in the folder?

Yes, That is correct the oscdimg.exe file is missing.

**Comment by YarNSD** [comment]
Also a problem with oscdimg.exe

On step 4, I select a location to save the image.

The "Get oscdimg" button is inactive.
When clicking "Create ISO", an error appears:
"Failed to create: The command cannot be executed due to the following error: This version..." the error description is cut off due to window limitations.
Assessment and Deployment Kit is installed
I downloaded the oscdimg utility from the repository and placed it in the directory "C:\Program Files (x86)\Windows Kits\10\Assessment and Deployment Kit\Deployment Tools\amd64\Oscdimg\"
Windows 11 Pro version 23H2 22631.4460

I apologize for possible grammatical errors

**Comment by YarNSD** [comment]
Also a problem with oscdimg.exe

On step 4, I select a location to save the image.

The "Get oscdimg" button is inactive.
When clicking "Create ISO", an error appears:
"Failed to create: The command cannot be executed due to the following error: This version..." the error description is cut off due to window limitations.
Assessment and Deployment Kit is installed
I downloaded the oscdimg utility from the repository and placed it in the directory "C:\Program Files (x86)\Windows Kits\10\Assessment and Deployment Kit\Deployment Tools\amd64\Oscdimg"
Windows 11 Pro version 23H2 22631.4460

I apologize for possible grammatical errors

Video:
https://github.com/user-attachments/assets/5ad29cb3-695d-4275-8b1d-2789bc5470c9

**Comment by lepiing** [comment]
Hey everyone, I just wanted to share a quick workaround for this issue while we wait for a permanent solution from Memory in the future.

1. Download oscdimg.exe from here https://github.com/memstechtips/WIMUtil/tree/main/assets/executables

2. After you get the error message **Signature date mismatch!** exit the utility and go to _C:\Program Files (x86)\Windows Kits\10\Assessment and Deployment Kit\Deployment Tools\amd64\Oscdimg_ and paste the oscdimg.exe in there.

3. Restart the whole process and you should get the **oscdimg verified and ready to use.** message.

not sure if it updates real-time so take the safe route and redo the whole thing.

**Comment by StarMusa88** [comment]
> Hey everyone, I just wanted to share a quick workaround for this issue while we wait for a permanent solution from Memory in the future.
> 
> 1. Download oscdimg.exe from here https://github.com/memstechtips/WIMUtil/tree/main/assets/executables
> 2. After you get the error message **Signature date mismatch!** exit the utility and go to _C:\Program Files (x86)\Windows Kits\10\Assessment and Deployment Kit\Deployment Tools\amd64\Oscdimg_ and paste the oscdimg.exe in there.
> 3. Restart the whole process and you should get the **oscdimg verified and ready to use.** message.
> 
> not sure if it updates real-time so take the safe route and redo the whole thing.


Hi Lepiing,

Thanks! that worked for me I downloaded the source file and copy and pasted the  oscdimg.exe in the required folder and viola it worked.

**Comment by StarMusa88** [comment]
memstechtips :

Now that I resolved the first issue I have this Error in VirtualBox.

![Screenshot 2024-11-16 134614](https://github.com/user-attachments/assets/cd8d94ba-5fbf-4461-9812-637bb36cecc2)

**Comment by memstechtips** [comment]
> Hey everyone, I just wanted to share a quick workaround for this issue while we wait for a permanent solution from Memory in the future.
> 
> 1. Download oscdimg.exe from here https://github.com/memstechtips/WIMUtil/tree/main/assets/executables
> 2. After you get the error message **Signature date mismatch!** exit the utility and go to _C:\Program Files (x86)\Windows Kits\10\Assessment and Deployment Kit\Deployment Tools\amd64\Oscdimg_ and paste the oscdimg.exe in there.
> 3. Restart the whole process and you should get the **oscdimg verified and ready to use.** message.
> 
> not sure if it updates real-time so take the safe route and redo the whole thing.

Hey there, thanks for the temporary fix!
I'm still working on a permanent fix.


> Now that I resolved the first issue I have this Error in VirtualBox.
> 
> ![Screenshot 2024-11-16 134614](https://private-user-images.githubusercontent.com/142222631/386870723-cd8d94ba-5fbf-4461-9812-637bb36cecc2.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzE3OTc5ODcsIm5iZiI6MTczMTc5NzY4NywicGF0aCI6Ii8xNDIyMjI2MzEvMzg2ODcwNzIzLWNkOGQ5NGJhLTVmYmYtNDQ2MS05ODEyLTYzN2JiMzZjZWNjMi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMTE2JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTExNlQyMjU0NDdaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT01ZGM5ZTc2MDEyZTc4MWM5NzVjMzdkNTY5Y2RkOWEwMzU4OGNiODBlYjU0NDI3NWMyOTQzNjk5M2EwNGNjZmRmJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.UNqIY7rRsKuASvyJQySverJTZQx_-pmUPAHG_Ile3os)

Tell me, did you use the Extract Drivers function to extract drivers to the image? If you did, it extracted the drivers of your main system and I've seen that the installation in VM's fail in the way you show in the screenshot.

**Comment by StarMusa88** [comment]
https://github.com/memstechtips : That Worked!  Thank you for your hard work... I will be using this tool often.


![Screenshot 2024-11-16 185858](https://github.com/user-attachments/assets/907a38a5-15bc-4728-91a5-8939c7530bd8)

**Comment by memstechtips** [comment]
This issue was fixed in #12
