### ISSUE TITLE
Feature request: Able to save windows apps

### ISSUE THREAD

**Issue by hendrikbez** [memstechtips/WIMUtil#6]
Hi, I do not know if this is the correct place to ask for this.

If it is possible, can there be a way to choose windows apps that is needed, so not to install them again.

**Comment by memstechtips** [comment]
This is a little above the scope of the project currently so it won't be implemented soon, but it is an idea for the future.

Can you close this issue and then just post it again in the discussions tab in the ideas section.

I'll use that discussion thread for ideas as I continue developing the app.
